package pqt.dss.itReq.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 28 19:27:01 PKT 2016
// ---------------------------------------------------------------------
public interface ITreqAppl extends ApplicationModule {
    void Apply();


    void DssApprove();

    void callWorkflow(oracle.jbo.domain.Number p_document_id, String ApprovalType);

    void DeleteCommit();

    void callITWorkflow(oracle.jbo.domain.Number p_document_id);
}

