package pqt.dss.itReq.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 23 17:53:35 PKT 2017
// ---------------------------------------------------------------------
public interface DssItReqHeaderView extends ViewObject {
    void itReqSearchUser();

    void setNVC_WfDocumentId(oracle.jbo.domain.Number value);
}

